### PR TITLE
Updates react support to v18

### LINKED ISSUE #45: Modern versions of react not supported.
The `react-lazy-images` package has a peer dependency of [react 15 or 16 ](https://github.com/fpapado/react-lazy-images/blob/2ec1f3e8af423295b23b7dbf05c6ab1cd30f6982/package.json#L72) this means we cannot use it with react 17 or 18 and npm 8.  NPM 8 requires peer dependencies to be installed.

### PR DESCRIPTION
**Pull request by radfahrer**
Updates various dependencies to support React 18. Also updates to latest version of react-intersection-observer.

This resolves #45 & #46

### CODE REVIEW

**Comment by radfahrer** [comment]
@fpapado could you take a look at the changes I'm proposing? These updates would allow us to keep using `react-lazy-images` while also keeping current on other major dependencies.

**Review by fpapado — APPROVED** [review]
Hi @radfahrer, thank you so much for the contribution! The changes look good to me, I will look at merging and releasing them this week, likely as a v2, just to hint to people that they should check their dependencies.

Can I ask, how are you using the library in practice? Does it address cases that `img[loading=lazy]` does not cover? I wrote this libary years ago, before lazy-loading was in the platform, so I am not sure what use cases people have nowadays. It doesn't change anything for the PR, mostly my curiosity 😁

**Comment by radfahrer** [comment]
@fpapado any update on getting this merged?

**Comment by fpapado** [comment]
Thank you @radfahrer! I'll merge this now and make a release tomorrow when I take some work time for it.

**Comment by radfahrer** [comment]
@fpapado any update on getting a release out?

**Comment by radfahrer** [comment]
@fpapado we are anxiously awaiting a release so that we can update our shared dependencies. Is there anything holding a release up?

**Comment by tarngerine** [comment]
bump on release?

**Comment by TheAlphamerc** [comment]
@radfahrer waiting for the release to support React v18.

**Comment by radfahrer** [comment]
> @radfahrer waiting for the release to support React v18.

We ended up forking and publishing to a private GitHub packages instance. I think with the current state of things the publish script will not work.

**Pull request merged**
